// export const ADD_TODO = 'todoLists/addTodo'
// export const SET_SEARCH_FILTER = 'filters/setSearchFilterChange'
// export const STATUS_FILTER_CHANGE = 'filters/statusFilterChange'
// export const PRIORITY_FILTER_CHANGE = 'filters/priorityFilterChange'
// export const TOGGLE_TODO_STATUS = 'todoLists/toggleTodoStatus'